name: arianth
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+9

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  cached_network_image: 3.4.1
  file_picker: ^11.0.2
  flutter_riverpod:
  get:
  connectivity_plus:
  url_launcher:
  fluttertoast:
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  shared_preferences:
  share_plus:
  intl: ^0.20.2
  pdfx: ^2.5.0          # Used to render the PDF page to an image
  internet_file: ^1.2.0
  google_mlkit_text_recognition:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  dio:
  android_intent_plus:
  image_picker: ^1.2.1
  in_app_update: ^4.0.2
  upgrader: ^13.1.0
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/tara_logo_color.jpeg"


flutter:


  uses-material-design: true


  assets:
    - assets/image/

